# Generated by Django 4.1.2 on 2022-10-23 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.CharField(blank=True, max_length=600, null=True)),
                ('term', models.CharField(blank=True, max_length=600, null=True)),
                ('prize_usd', models.FloatField(default=0)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('tasks', models.JSONField(blank=True, null=True)),
                ('winners', models.JSONField(blank=True, null=True)),
                ('is_exact_time', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.ManyToManyField(blank=True, related_name='following_event', to=settings.AUTH_USER_MODEL)),
                ('joined', models.ManyToManyField(blank=True, related_name='joined_event', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.CharField(blank=True, max_length=600, null=True)),
                ('token_amount', models.FloatField(default=0)),
                ('token_in_usd', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='project.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('chain_id', models.CharField(default='bsc_mainnet', max_length=50)),
                ('address', models.CharField(db_index=True, max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(default='ERC20', max_length=20)),
                ('total_supply', models.FloatField(default=0)),
                ('decimals', models.IntegerField(default=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('content', models.CharField(max_length=1000)),
                ('rate', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('id_string', models.CharField(db_index=True, max_length=200)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=600, null=True)),
                ('taxonomy', models.CharField(default='tag', max_length=10)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='media.media')),
            ],
            options={
                'unique_together': {('id_string', 'taxonomy')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('id_string', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('desc', models.CharField(blank=True, max_length=600, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_backer', models.BooleanField(default=False)),
                ('links', models.JSONField(blank=True, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='media.media')),
                ('properties', models.ManyToManyField(blank=True, related_name='projects', to='project.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunted_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('value', models.FloatField(default=0)),
                ('value_usd', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='project.event')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='project.token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncentiveDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('earned', models.FloatField(default=0)),
                ('is_claimed', models.BooleanField(default=False)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_distributions', to='project.incentive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incentive',
            name='token_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='project.token'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_events', to='project.project'),
        ),
        migrations.AddField(
            model_name='event',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='events', to='project.property'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
