# Generated by Django 4.1.2 on 2022-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='timeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
