# Generated by Django 4.1.2 on 2022-10-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_event_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_string',
            field=models.CharField(db_index=True, default=2, max_length=200),
            preserve_default=False,
        ),
    ]
