# Generated by Django 4.1.2 on 2022-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_event_id_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='chain_id',
            field=models.CharField(default='56', max_length=50),
        ),
    ]
