# Generated by Django 4.1.2 on 2022-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_token_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='credits',
            field=models.FloatField(default=0),
        ),
    ]
