# Generated by Django 4.1.2 on 2022-11-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('authentication', '0002_profile_remove_wallet_bio_remove_wallet_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='media.media'),
        ),
    ]
