# Generated by Django 4.1.2 on 2022-11-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitee', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refer_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
